### ISSUE TITLE
En internal Error occured and should be reported

### ISSUE THREAD

**Issue by heschy2** [hwittenborn/celeste#175]
So, I am syncing between NextCloud and Celeste, but Celeste is very unstable (I installed it like 5 minutes ago and it already crashed multiple times after doing nothing). Now it said that an error occured that was celestes fault and should be reported.

```
thread 'main' panicked at src/launch.rs:1805:34:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "Datei oder Verzeichnis nicht gefunden" }
stack backtrace:
````

Translation for [DE]`Datei oder Verzeichniss nicht gefunden`: File or Directory not found.

**Comment by hwittenborn** [comment]
Hey @heschy2, does restarting Celeste fix the issue? It looks like that issue is from Celeste trying to read a file that doesn't exist, which (I'm pretty sure) should only happen if Celeste registers a file as needing transferred, and then you deleting it quickly after before Celeste finishes doing stuff with it.

**Comment by heschy2** [comment]
Yes, the problem no longer occures. However, I didn't delete any of the Files synced, and no proccess on my system would have any reason to even change any of those Files.

**Comment by hwittenborn** [comment]
Hey @heschy2, I'm not quite sure what might've been causing the issue in that area. It looks like Celeste is just checking the metadata of a file (during a file sync) there, so I'm not quite sure what could have been causing the issue.

I'm gonna go ahead and close this since you're not able to experience it anymore, let me know if you do and I can get this re-opened though (you can also open a new issue if you feel it's more appropriate).
