### ISSUE TITLE
Invalid name error when attempting to login to Dropbox

### ISSUE THREAD

**Issue by clauseggers** [hwittenborn/celeste#184]
When I attempt to login to my Dropbox I get an ‘Invalid name. Names must …’ error. This is because the mask you are using is incorrect. My login name is the email address I used to create the Dropbox account with. Celeste is incorrectly saying that @ can not be used.

**Comment by hwittenborn** [comment]
Hey @clauseggers, it looks like you encountered a similar issue to https://github.com/hwittenborn/celeste/issues/149, I guess the new name just wasn't any less confusing :p.

You can name that whatever you want (I just have it named `Dropbox` since it's my only Dropbox connection), you'll enter your email in a browser window after clicking the `Log in` button.

Do you have any ideas for what that field could be renamed to? You're far from the first person to get misled by that, and I'm definitely wanting to fix things to avoid that confusion.

I'll go ahead and get this closed, if you think this should be re-opened just let me know though! If you have any other issue feel free to open a new one as well.

**Comment by clauseggers** [comment]
Hi Wittenborn, thank you for getting back to me. Yes "name" could mean a lot of things ;-) Perhaps you could do like in web forms where sometimes the individual fields come filled with an explanatory text in a light grey, and that text disappears as soon as the user puts the cursor in the field. That text could be something like "Give this connection a unique name".

Now for the next issue: I hooked it up to Dropbox, but I get no files or folders listed in Celeste. I can't see any network traffic going on either. Try hooking it up again or let it run in the background?

**Comment by clauseggers** [comment]
I tried to delete the Dropbox account and start over, but Celeste crashes when I press 'delete'.

Log says
```
--- Running report_uReport ---
Error: No segments found in coredump './coredump'
('report_uReport' exited with 1)

```
